run:
  go: "1.18"
  concurrency: 4

  # let's skip over the dirs container 'older' meteor code
  skip-dirs:
    - controllers/meteor
    - controllers/shower

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
