presets:
- env:
  - name: XDG_CACHE_DIR
    value: /tmp/.cache
  - name: GOCACHE
    value: /tmp/.cache/go-build
  - name: HOME
    value: /tmp/.cache
presubmits:
- always_run: true
  context: op1st/prow/pre-commit
  decorate: true
  name: pre-commit
  skip_report: false
  spec:
    containers:
    - command:
      - pre-commit
      - run
      - --all-files
      image: quay.io/thoth-station/thoth-precommit-py38:v0.15.0
- always_run: true
  context: thoth-station/prow/make-test
  decorate: true
  name: make-test
  skip_report: false
  spec:
    containers:
    - command:
      - make
      - test
      image: docker.io/golang:v0.15.0
