apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    name: pipelinerun-finalize
rules:
    - apiGroups:
          - tekton.dev
      resources:
          - pipelineruns/finalizers
      verbs:
          - "*"
    - apiGroups:
          - meteor.operate-first.cloud
      resources:
          - meteors/finalizers
      verbs:
          - update
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: pipelinerun-finalize
subjects:
    - kind: ServiceAccount
      name: pipeline
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: pipelinerun-finalize
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: meteor-external
    namespace: opf-jupyterhub
subjects:
    - kind: ServiceAccount
      name: pipeline
      namespace: aicoe-meteor
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: meteor-external
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    name: meteor-external
    namespace: opf-jupyterhub
rules:
    - apiGroups:
          - image.openshift.io
      resources:
          - imagestreams/layers
          - imagestreams
      verbs:
          - "*"
    - apiGroups:
          - route.openshift.io
      resources:
          - routes
          - routes/status
      verbs:
          - get
          - list
          - watch
    - apiGroups:
          - meteor.operate-first.cloud
      resources:
          - meteorcomas/finalizers
      verbs:
          - update
