---
apiVersion: meteor.zone/v1alpha1
kind: CustomeRuntimeEnvironment
metadata:
  name: s2i-minimal-py38-notebook-import-with-secret # TODO
  labels:
    app.kubernetes.io/created-by: cpe-_a-meteor.zone-CNBi-v0.1.0
  annotations:
    opendatahub.io/notebook-image-name: s2i-minimal-py38-notebook
    opendatahub.io/notebook-image-desc: minimal notebook image for python 3.8 from my private repository
    opendatahub.io/notebook-image-creator: goern
spec:
  buildType: ImageImport
  fromImage: quay.io/goern/private-s2i-minimal-py38-notebook:v0.2.2
  imagePullSecret:
    name: private-registry-credentials
---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJ0ZXN0IiwicGFzc3dvcmQiOiJ0ZXN0IiwiYXV0aCI6ImRHVnpkRHAwWlhOMCJ9fX0=
kind: Secret
metadata:
  name: private-registry-credentials
type: kubernetes.io/dockerconfigjson
