---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cre-gitrepo
  labels:
    app.kubernetes.io/part-of: meteor-operator
spec:
  description: Build an image suitable for experiments in JupyterHub, including all dependencies resolved by Thoth Station
  params:
    - name: url
      type: string
    - name: ref
      type: string
      default: ""
    - name: name
      description: Image name
      type: string
    - name: description
      description: Custom description
      type: string
    - name: creator
      description: Owner, user who requested the import
      type: string

  workspaces:
    - name: data
    - name: sslcertdir
      optional: true

  tasks:
    - name: git-clone
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
        - name: output
          workspace: data
      params:
        - name: url
          value: $(params.url)
        - name: revision
          value: $(params.ref)
        - name: subdirectory
          value: repo

    - name: generate
      taskRef:
        name: generate-jupyterhub
      runAfter:
        - git-clone
      workspaces:
        - name: data
          workspace: data
      params:
        - name: url
          value: $(params.url)

    - name: buildah
      taskRef:
        name: buildah
        kind: ClusterTask
      runAfter:
        - generate
      workspaces:
        - name: source
          workspace: data
      params:
        - name: IMAGE
          value: image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/$(context.pipelineRun.name)

    - name: create-image-stream
      taskRef:
        name: openshift-client
        kind: ClusterTask
      runAfter:
        - buildah
      params:
        - name: SCRIPT
          value: |
            cat <<EOM | oc apply -f -
            ---
            kind: ImageStream
            apiVersion: image.openshift.io/v1
            metadata:
              annotations:
                opendatahub.io/notebook-image-name: $(params.name)
                opendatahub.io/notebook-image-desc: "$(params.description)"
                opendatahub.io/notebook-image-url: $(params.url)
                opendatahub.io/notebook-image-creator: $(params.creator)
                opendatahub.io/notebook-image-origin: Admin
              name: $(context.pipelineRun.name)
              namespace: $(context.pipelineRun.namespace)
              labels:
                opendatahub.io/notebook-image: 'true'
                app.kubernetes.io/part-of: meteor-operator
            spec:
              lookupPolicy:
                local: true
              tags:
                - name: latest
            EOM
